### PR TITLE
Added jUnit reports for jest tests needed for Jenkins builds

### PR DESCRIPTION
**Pull request by spetrov**
This PR request is needed for the Jenkins integration - builds and tests.

### CODE REVIEW

**Comment by spetrov** [comment]
run tests

**Comment by spetrov** [comment]
run tests

**Comment by spetrov** [comment]
run tests

**Comment by spetrov** [comment]
run tests

**Comment by spetrov** [comment]
run tests

**Comment by spetrov** [comment]
run tests

**Review by cerebrl — APPROVED** [review]
Looks good.

**Pull request merged**
